### ISSUE TITLE
Showing unwatched episode when set to last episode.

### ISSUE THREAD

**Issue by IZZO21** [MadDogTen/MTrack#2]
When attempting to set my current episode as the last episode MTracker will still tell me I have an episode left to watch. Only way to get rid of it is to watch it.

**Comment by IZZO21** [comment]
After looking more closely I now see the option "Reset to..." in there and you can reset it to the end and that will fix the problem. You may want to merge the the "set Season + Episode" and the "Reset to" options.

**Comment by MadDogTen** [comment]
Settings were merged as suggested.
